const ERROR = 'ERROR';
const LOADING = 'LOADING';
const SEARCH = 'SEARCH';
const POSTS = 'POSTS';
const BREADCRUMBS = 'BREADCRUMBS';
const SET_USER = 'SET_USER';
const GET_USER = 'GET_USER';
const SET_CURRENT_USER = 'SET_CURRENT_USER';
const USER = 'USER';
const USERS = 'USERS';
const POST_DELETE = 'POST_DELETE';
const USER_DELETE = 'USER_DELETE';
const USER_SELECT = 'USER_SELECT';
const USER_UPDATE = 'USER_UPDATE';
const ALL_USERS = 'ALL_USERS';
const IS_VALID = 'IS_VALID';
const REFRESH = 'REFRESH';
const AUTHENTICATE = 'AUTHENTICATE';
const AUTHORIZE = 'AUTHORIZE';
const PURGE = 'PURGE';
export {
  ERROR,
  LOADING,
  SEARCH,
  POSTS,
  BREADCRUMBS,
  SET_USER,
  GET_USER,
  SET_CURRENT_USER,
  USER,
  USERS,
  POST_DELETE,
  USER_SELECT,
  USER_DELETE,
  USER_UPDATE,
  ALL_USERS,
  IS_VALID,
  REFRESH,
  AUTHENTICATE,
  AUTHORIZE,
  PURGE
};
